server:
  port: 18967
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: systemGate
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1

        - id: bepGate
          uri: lb://bep
          predicates:
            - Path=/bep/**
          filters:
            - StripPrefix=1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
logging:
  config: classpath:${spring.application.name}-logback.xml
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000